// Generated file - placeholder for build_runner generation
// This file will be generated when running: flutter packages pub run build_runner build

// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'database_providers.dart';

// Placeholder for Riverpod generated code
// The actual implementation will be generated by riverpod_generator
