// Generated file - placeholder for build_runner generation
// This file will be generated when running: flutter packages pub run build_runner build

// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'message_model.dart';

// Placeholder for Isar generated code
// The actual implementation will be generated by isar_generator
