// Generated file - placeholder for build_runner generation
// This file will be generated when running: flutter packages pub run build_runner build

// coverage:ignore-file
// GENERATED CODE - DO NOT MODIFY BY HAND
// ignore_for_file: type=lint
// ignore_for_file: unused_element, deprecated_member_use, deprecated_member_use_from_same_package, use_function_type_syntax_for_parameters, unnecessary_const, avoid_init_to_null, invalid_override_different_default_values_named, prefer_expression_function_bodies, annotate_overrides, invalid_annotation_target, unnecessary_question_mark

part of 'api_response.dart';

// Placeholder - will be generated by freezed
class _$ApiResponse<T> {}
class Success<T> extends _$ApiResponse<T> {
  const Success(this.data);
  final T data;
}
class Error<T> extends _$ApiResponse<T> {
  const Error(this.message, [this.statusCode]);
  final String message;
  final int? statusCode;
}
