// Generated file - placeholder for build_runner generation
// This file will be generated when running: flutter packages pub run build_runner build

// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'message.dart';

// Placeholder - will be generated by json_annotation
Message _$MessageFromJson(Map<String, dynamic> json) => Message(
  id: json['id'] as int,
  serverId: json['serverId'] as String?,
  title: json['title'] as String,
  content: json['content'] as String,
  category: json['category'] as String,
  isViewed: json['isViewed'] as bool? ?? false,
  isFavorite: json['isFavorite'] as bool? ?? false,
  date: DateTime.parse(json['date'] as String),
  updatedAt: DateTime.parse(json['updatedAt'] as String),
);

Map<String, dynamic> _$MessageToJson(Message instance) => <String, dynamic>{
  'id': instance.id,
  'serverId': instance.serverId,
  'title': instance.title,
  'content': instance.content,
  'category': instance.category,
  'isViewed': instance.isViewed,
  'isFavorite': instance.isFavorite,
  'date': instance.date.toIso8601String(),
  'updatedAt': instance.updatedAt.toIso8601String(),
};
