// Generated file - placeholder for build_runner generation
// This file will be generated when running: flutter packages pub run build_runner build

// coverage:ignore-file
// GENERATED CODE - DO NOT MODIFY BY HAND
// ignore_for_file: type=lint
// ignore_for_file: unused_element, deprecated_member_use, deprecated_member_use_from_same_package, use_function_type_syntax_for_parameters, unnecessary_const, avoid_init_to_null, invalid_override_different_default_values_named, prefer_expression_function_bodies, annotate_overrides, invalid_annotation_target, unnecessary_question_mark

part of 'message.dart';

// Placeholder - will be generated by freezed
class _$Message {
  const _$Message({
    required this.id,
    this.serverId,
    required this.title,
    required this.content,
    required this.category,
    this.isViewed = false,
    this.isFavorite = false,
    required this.date,
    required this.updatedAt,
  });
  
  final int id;
  final String? serverId;
  final String title;
  final String content;
  final String category;
  final bool isViewed;
  final bool isFavorite;
  final DateTime date;
  final DateTime updatedAt;
}

class _Message extends _$Message {
  const _Message({
    required super.id,
    super.serverId,
    required super.title,
    required super.content,
    required super.category,
    super.isViewed = false,
    super.isFavorite = false,
    required super.date,
    required super.updatedAt,
  });
}
